[brick]
name = "ArgParse"
version = "0.1.0"
chplVersion = "1.25.0"
license = "None"
tests = ["argParseTests.chpl",
         "masonArgParseTests.chpl"]

[dependencies]

[examples]
examples = ["masonArgParseExample.chpl"]

[examples.masonArgParseExample]
# TODO: find out if we can support $CHPL_HOME in path, or if we do already
execopts = "arg1 --flagOn subCmd1 subVal1"
